const TELAS = {
  TELA_PRINCIPAL: 'TELA_PRINCIPAL',
  TELA_CADASTROS: 'TELA_CADASTROS',
  TELA_LANCAMENTO: 'TELA_LANCAMENTO',
  TELA_EXTRATOS: 'TELA_EXTRATOS',
  TELA_USUARIO: 'TELA_USUARIO',
  
  TELA_LOGIN: 'TELA_LOGIN',
  TELA_NOVO_USUARIO: 'TELA_NOVO_USUARIO'
};

export default TELAS;
